### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by SY-Xuan** [eric-ai-lab/CPL#1]
It seems that you forgot to import this part:
https://github.com/eric-ai-lab/CPL/blob/16274a860712e7674a8d8fea7f3046fd96a065e4/CPL/trainers/cocoopcf.py#L17

And you also missed the requirements.txt.

**Comment by jkooy** [comment]
Hi, I am sorry, what do you mean by forgot to import?
For requriements, sorry for missing. It should be the same as the CoCoOp one.

**Comment by SY-Xuan** [comment]
`from utils import solver, mupdate`
I cannot find anything of these two functions.

**Comment by jkooy** [comment]
It seems to be merged when I cleant it up. Let me add it. Thks for pointing it out!

**Comment by SY-Xuan** [comment]
Good work!!! I close this issue!
