### ISSUE TITLE
Is the code for getting the semantically nearest sentence within a batch missing?

### ISSUE THREAD

**Issue by pengzhansun** [eric-ai-lab/CPL#3]
Hi Xuehai,

Thanks for your solid and nice work. I'm very interested in it and trying to reproduce the experiment results, but I have encountered some problems:

1) The sharing link for BERTScore matrix is not working. https://drive.google.com/drive/folders/1kvFEQUdeZ5scjTWrLWdhE4BJIbzJpFbY?usp=sharing
2) I cannot find the code about getting the semantically nearest sentence using BERTscore within a batch given a query sentence. In particular, I guess the code is missing for line 17 in the pseudo code of CPL algorithm shown in the paper.

It would be much appreciated if you can help, thx in advance:)

**Comment by jkooy** [comment]
Hi pengzhansun,

Many thanks for your interests in the work.
The code for getting the semantically nearest sentence within a batch is here 
https://github.com/eric-ai-lab/CPL/blob/ce47190b110ec6807081dd70571454b8c23368c4/CPL/trainers/cocoopcf.py#L337

For your problems
1. I will host it here https://www.dropbox.com/sh/wlxf57tes2i90y9/AABua93wLCshghMjEd0_GNXpa?dl=0
2. The code is here by computing the score and save it to a dict. https://github.com/eric-ai-lab/CPL/blob/ce47190b110ec6807081dd70571454b8c23368c4/CPL/trainers/cocoopcf.py#L205
And your have to initial it here each time
https://github.com/eric-ai-lab/CPL/blob/ce47190b110ec6807081dd70571454b8c23368c4/CPL/trainers/cocoopcf.py#L220
Hope it helps.

**Comment by pengzhansun** [comment]
Thanks for your response, it helps a lot:)
